version: 2.1

workflows:
  version: 2.1
  lint-build-deploy:
    jobs:
      - lint
      - build
      - deploy:
          filters:
            branches:
              only: dev
          requires:
            - lint
            - build

commands:
  install_modules:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install && cd server && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  lint:
    docker:
      - image: node
    steps:
      - install_modules
      - run: npm run lint

  build:
    docker:
      - image: node
    steps:
      - install_modules
      - run: npm run build
      - persist_to_workspace:
          root: mess-build
          paths: ./* 

  deploy:
    docker:
      - image: node
    steps:
      - attach_workspace:
          at: mess-build
      - run: git config --global user.email "abdatta@iitk.ac.in"
      - run: git config --global user.name "Abhishek Datta"
      - run: git clone https://$DEV_BUILD_USER:$DEV_BUILD_PASS@github.com/abdatta/hall3-mess-build.git
      - run: mv hall3-mess-build/.git mess-build/.git
      - run: mv hall3-mess-build/.git* mess-build
      - run: cd mess-build && git status
      - run: cd mess-build && git add .
      - run: cd mess-build && git commit -m "Update dev build on `date` from circle-ci"
      - run: cd mess-build && git push
      - run: "curl --fail -X POST -H 'X-Deploy-Token: '$DEPLOY_TOKEN $DEV_DEPLOY_URL"
