# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci && cd server && npm ci
      - run: npm run prod
      - name: Upload the production build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: prod-build
          path: ./mess-build-prod
          if-no-files-found: error
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Deploy
    strategy:
      matrix:
        node-version: [10.x]
    env:
      build_url: ${{ secrets.PROD_BUILD_REPO_URL }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: prod-build
          path: ./prod-build
      - name: Pull build repo
        run: git clone "${build_url}"
      - name: Replace with new build
        run: |
          cd mess-build-prod
          rm -rf public
          rm -rf src
          cp -rf ../prod-build/. ./
          git diff
      - name: Install build
        run: |
          cd mess-build-prod
          npm install --production
      - name: Push build repo
        run: |
          cd mess-build-prod
          git config user.name "Github Actions CI"
          git config user.email "hall3web+ci@gmail.com"
          git remote set-url origin "${build_url}"
          git push origin master
